### ISSUE TITLE
MQTT Auto Discovery with multiple Bolt EVs

### ISSUE THREAD

**Issue by podux** [michaelwoods/onstar2mqtt#109]
Really excited to add this to my home assistant. Is there a way to get this working with multiple Bolt EVs? I'm currently trying to run it with 2 separate docker instances each pointing to a different VIN, but when they publish to my HA MQTT, I think they're all going into the same sensor (sensor.ev_*). Is there a way that I can influence the auto discovery capability in HA to have 2 sets of these sensors?

Thanks for your work on this

**Comment by jostrander** [comment]
I just spent some time troubleshooting this myself, and it appears that the VIN env parameter is ignored, and only the first vehicle returned by OnstarJS is actually subscribed to in this library:

https://github.com/michaelwoods/onstar2mqtt/blob/main/src/index.js#L102

I may work on a pull request to fix this if I can get it working for myself.

**Comment by jostrander** [comment]
I don't know what would be the most desired behavior, but I changed it to work for what I would think people might want for autodiscovery with multiple vehicles. With the changes I've made it still requires 2 instances as the underlying library sets its self up on a per-VIN basis. That could be changed, but it was more in-depth than I wanted to go without discussion here. 

Anyway, there are a couple of changes to the index.js

```diff
+const getCurrentVehicle = async commands => {
+    const vehicles = await getVehicles(commands);
+    const currentVeh = _.find(vehicles, v => v.vin.toLowerCase() === onstarConfig.vin.toLowerCase()); 
+    if (!currentVeh) {
+        throw new Error(`Configured vehicle VIN ${onstarConfig.vin} not available in account vehicles`);
+    }
+    return currentVeh;
+}
```
and 
```diff
         const commands = init();
-        const vehicles = await getVehicles(commands);
+        const vehicle = await getCurrentVehicle(commands);
 
-        const mqttHA = new MQTT(vehicles[0], 'homeassistant');
+        const mqttHA = new MQTT(vehicle, 'homeassistant');
...
-            const v = vehicles[0];
+            const v = vehicle;
```
and one change in MQTT.js (as well as updating the references to this static method to instance references)

```diff
-    static convertFriendlyName(name) {
-        return _.startCase(_.lowerCase(name));
+    convertFriendlyName(name) {
+        return _.startCase(_.lowerCase(`${this.vehicle} ${name}`));
     }
```

The latter is more for convenience. It does make the sensor names long in HA (`sensor.2021_chevrolet_bolt_odometer`) instead of `sensor.odometer`, but it makes it clear unless you have two of the exact vehicles on your account. 

---

If this seems doable I'll PR my changes, for now this seems to be working for me.

**Comment by podux** [comment]
Thanks for this. I'm going to give it a try with one small tweak. In the MQTT.js, instead of making the friendly name based upon ${name} I'm going to use ${vin} for now. I have the unique case of having 2 2017 Bolts :-)

**Comment by jostrander** [comment]
You can use `this.vehicle.vin` or in the constructor the instance name is actually set to the same, so you could use `this.instance` for VIN. I also noticed I missed the tire pressures since they have custom names. I'm thinking ultimately this would be something you might want to simply configure per instance via ENV. For me the names are absurdly long once you add the year/make/model/trim/config then the sensor name with units etc.

**Comment by jostrander** [comment]
@podux I added a PR that actually uses the custom prefix instead of pre-prending the year/make/model. Maybe that is better for your scenario where you can identify them now however you want per docker instance.
